version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u manage.py
    ports:
      - "5000:5000"
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - .:/app
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 'docker_mysql'
    command: ['mysqld', '--character-set-server=utf8']
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:
networks:
  frontend:
  backend:
